spring:
  datasource:
    username: liefersoft_owner
    password: liefersoft
    url: jdbc:postgresql://localhost:5432/liefersoftdb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
